### PR TITLE
Add static Header component. WIP. Don't merge!

### PR DESCRIPTION
**Pull request by ltclmbdev**
WIP. Don't merge!

### CODE REVIEW

**Comment by trevordmiller** [comment]
I feel like maybe this should be done directly in the egghead.io project since this isn't a promoted shared component across projects - same thing with the footer component. IMO egghead-ui should only contain components shared across egghead projects. cc: @joelhooks what do you think?

**Comment by joelhooks** [comment]
You are correct, all brand new components should be developed in their respective targets (instructor center, Rails app, consumer React app (working title), review app). 

Any environment where "WIP DO NOT MERGE" is not required. 

I do this because it is easier for me and I can hack around without it breaking stuff or affecting others (version bumps and whatnot). 

If I wanted to share code for review, I would fork and use the fork to PR into my working branch on this repo.

**We should never have "NO MERGE" PRs**. It only causes problems.

**Comment by ltclmbdev** [comment]
Got it! Transferring stuff to the rails and close PR

**Comment by trevordmiller** [comment]
@DrShpongle Can you also remove `Footer` as it is not shared across projects and should only be in egghead-rails/client for now.

**Comment by ltclmbdev** [comment]
Will do, @trevordmiller

**Pull request closed without merging**
