### PR TITLE
Add custom egghead icons

### PR DESCRIPTION
**Pull request by trevordmiller**
# Changes

- Add custom egghead icons from new `react-icons` fork: https://github.com/eggheadio/react-icons

Font awesome still works just fine and can continue to be in `egghead-ui` until we replace all needed icons with custom ones. @justin808, you are good now to promote the egghead-rails custom icon svgs. I added a `README.md` and `CONTRIBUTING.md` to the react-icons fork for information on how it all works: https://github.com/eggheadio/react-icons.

# Result For User

screen shot 2017-04-07 at 3 28 31 pm
screen shot 2017-04-07 at 3 28 47 pm

---

### CODE REVIEW

**Comment by trevordmiller** [comment]
@vojtaholik The only icon missing from the the zip you gave me in https://github.com/eggheadio/egghead-instructor-center/issues/178 is the check bubble icon; this had some non-standard fill thing that wouldn't compile. I also figured icons like this (just a styling of an icon that already exists, in this case `check`) could just be done on the client? We could add a `RoundIcon` and `SquareIcon` which wraps an icon with a background color and border-radius instead of creating all these as SVGs. Just a thought. If you want the check bubble as an SVG, I can do that too but you'll need to export it with standard SVG fills.

**Comment by vojtaholik** [comment]
Some icons need to be centered manually (inside a bubble) so I'll adjust and provide you the missing one @trevordmiller 👍 Sounds good?

**Comment by trevordmiller** [comment]
@vojtaholik That's fine. If the icons are trimmed of extra space, the centering could be done programmatically to be mathematically centered. But yeah whatever works.

**Comment by trevordmiller** [comment]
I'm merging this manually so I can finish my PRs tonight; but if there is any feedback it is still welcome and I can address it in another PR.

**Comment by vojtaholik** [comment]
@trevordmiller If you can get the volumetric center (or optical center) of an icon mathematically, that'd be great of course. Found this helpful article: https://medium.com/@erqiudao/the-play-button-is-not-optical-alignment-4cea11bda175

Otherwise, I'd rather stick to delivering all the icons from me so you don't have to trouble with it. :) Thats my only concern.

**Comment by trevordmiller** [comment]
@vojtaholik Ok no worries. When you are ready to update icons, just submit a story to the egghead-ui project (https://github.com/eggheadio/egghead-ui/projects/2) and one of us will take care of it :) You can see what is currently in egghead-ui here: http://styleguide.egghead.io/?selectedKind=Icon&selectedStory=Info&full=0&down=1&left=1&panelRight=0

**Pull request merged**
